apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-deployment
  labels:
    app: tezos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tezos
  template:
    metadata:
      labels:
        app: tezos
    spec:
      containers:
      - name: tezos
        image: 358459329979.dkr.ecr.us-east-1.amazonaws.com/ubuntu-tezos
        imagePullPolicy: Always
        env:
        - name: testName1
          value: testValue1
        ports:
        - containerPort: 8732
        - containerPort: 8733
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
spec:
  selector:
    app: tezos
  ports:
    - protocol: TCP
      port: 8733
