apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-deployment
  labels:
    app: tezos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tezos
  template:
    metadata:
      labels:
        app: tezos
    spec:
      containers:
      - name: tezos
        image: ubuntu-tezos
        imagePullPolicy: Never
        env:
        - name: testName1
          value: testValue1
        command: ["docker run -i -t ubuntu-tezos"]
        ports:
        - containerPort: 8732
