apiVersion: v1
kind: ConfigMap
metadata:
  name: tezos-config
data:
  parameters.json: |
    {
      "bootstrap_accounts": [
        [
          "edpkubXzL1rs3dQAGEdTyevfxLw3pBCTF53CdWKdJJYiBFwC1xZSct",
          "4000000000000"
        ],
        [
          "edpkvUS1z9QGXr6f89dNF5WyeRCFuK6PYWYrMHcpU9kQ2TevD66fDG",
          "4000000000000"
        ],
        [
          "edpktezaD1wnUa5pT2pvj1JGHNey18WGhPc9fk9bbppD33KNQ2vH8R",
          "4000000000000"
        ]
      ],
      "preserved_cycles": 2,
      "blocks_per_cycle": 8,
      "blocks_per_commitment": 4,
      "blocks_per_roll_snapshot": 4,
      "blocks_per_voting_period": 64,
      "time_between_blocks": [
        "10",
        "20"
      ],
      "endorsers_per_block": 32,
      "hard_gas_limit_per_operation": "800000",
      "hard_gas_limit_per_block": "8000000",
      "proof_of_work_threshold": "-1",
      "tokens_per_roll": "8000000000",
      "michelson_maximum_type_size": 1000,
      "seed_nonce_revelation_tip": "125000",
      "origination_size": 257,
      "block_security_deposit": "512000000",
      "endorsement_security_deposit": "64000000",
      "endorsement_reward": [ "2000000" ],
      "cost_per_byte": "1000",
      "hard_storage_limit_per_operation": "60000",
      "test_chain_duration": "1966080",
      "quorum_min": 2000,
      "quorum_max": 7000,
      "min_proposal_quorum": 500,
      "initial_endorsers": 1,
      "delay_per_missing_endorsement": "1",
      "baking_reward_per_endorsement": [ "200000" ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-baker-deployment
  labels:
    app: tezos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tezos
      category: baker
  template:
    metadata:
      labels:
        app: tezos
    spec:
      containers:
      - name: tezos-node
        image: 358459329979.dkr.ecr.us-east-1.amazonaws.com/ubuntu-tezos
        imagePullPolicy: Always
        command: ["
        ports:
        - containerPort: 8732
        - containerPort: 8733
      - name: tezos-baker
        image: 358459329979.dkr.ecr.us-east-1.amazonaws.com/ubuntu-tezos
        command: ["base-dir/tezos-baker-006-PsCARTHA", "-A", "localhost", "-P", "8733", "-d", "/base-dir/client", "run", "with", "local", "node", "/base-dir/node", "baker"]
}

        imagePullPolicy: Always
      - name: tezos-endorser
        image: 358459329979.dkr.ecr.us-east-1.amazonaws.com/ubuntu-tezos
        imagePullPolicy: Always
        command: [""base-dir/tezos-endorser-006-PsCARTHA"" -A "localhost" -P "8733" -d "/base-dir/client", "run", "baker" ]
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
spec:
  selector:
    app: tezos
  ports:
    - protocol: TCP
      port: 8733
